# Generated by Django 5.1.7 on 2025-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Term Life', 'Term Life'), ('Health', 'Health'), ('Vechile', 'Vechile')], max_length=50)),
                ('premium', models.IntegerField()),
                ('coverage', models.IntegerField()),
            ],
        ),
    ]
